name: st_ev_cfg
description: builds scoretrader event config payload

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.11

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  equatable: ^2.0.3
  args: ^2.3.0
  json_annotation: ^4.4.0
  # grouped_list: ^4.1.0
  tuple: ^2.0.0
  riverpod: ^1.0.3
  # dotted_border: ^2.0.0+2
  # intl:

dev_dependencies:
  build_runner: ^2.1.7
  json_serializable: ^6.1.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
# flutter:
#   uses-material-design: true
#   # assets:
# flutter_intl:
#   enabled: true
